# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a047d716be68cb8b991faa5a490081cdcfbeb518543194dc093678e6adb9502a44c8ae267b251a4ffd79c313c8af5afbc8e3e1fa05b14fd54e7ba42efc8f2b0

test:
  secret_key_base: c05f578c202e0de3ecd3546dbb75cca0e937ca3d4cb233db6be402e449a5c1acc21ab308727b4f69d1f4301b9db31ed4502870442130227cdf1a9713b60c7267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
