# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f3c267f4a695ea6f9404d6db1e22fefb2eecbf32b166aba0eb1d0772f9d740770ed7f30268008af75a7f57f2b9b3676abf6ad3d5c376040aa44f383062c7c3

test:
  secret_key_base: ab19486cc3c1c80212db461f34ad1680f157955e6cbd76d255e67229ab40afab0ee9c6b35e539f590bfa5a8ab675bfbba8068cdc49c1ed7d03a42df4b0420a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
